id: P224F4BB0
initial_creation_type: input
source_metadata:
  title: Tāranātha Series
  language: en
  description: 'Texts by and about Jetsün Tāranātha (rje btsun tA ra nA tha, 1575–1634),
    translator, prolific author and the second most important figure in the Jonang
    lineage:'
  volume:
    374b241bf880459c9b076b3d9d8cb546:
      title: Brief Biography of Tāranātha
      parent: Biography
    a380d9d8f63c480785bff216b40c4698:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Biography
    edafb424acec4b74b1cdc39a01f95eb8:
      title: 'Flower of Faith: In Praise of Tāranātha, Lord of Secrets'
      parent: Praise
created_at: '2022-03-01T01:39:31.661952'
last_modified_at: '2022-03-01T01:39:31.661959'
